FROM python:3.12.4-bookworm

WORKDIR /develop

RUN apt update
RUN apt install git git-flow nano -y
COPY ./requirements.txt /requirements.txt

RUN pip install --no-cache-dir --upgrade -r /requirements.txt

COPY . .